import { BuildingType, BuildingCategory } from '../types/economy';

export const BUILDING_TYPES: Record<string, BuildingType> = {
  // Rural - Agriculture
  wheat_farm: {
    id: 'wheat_farm',
    category: BuildingCategory.RURAL,
    nameKey: 'building.wheat_farm',
    icon: 'building/wheat',
    inputs: {},
    outputs: { grain: 100 },
    workforceRequired: 500,
    arableLandRequired: 5,
    baseCost: 1000,
    costMultiplier: 1.0,
    levelCostMultiplier: 1.0,
    cityType: 'small',
    economyOfScale: false,
    maxEconomyOfScale: 0,
  },
  fishing_wharf: {
    id: 'fishing_wharf',
    category: BuildingCategory.RURAL,
    nameKey: 'building.fishing_wharf',
    icon: 'building/fish',
    inputs: {},
    outputs: { fish: 80 },
    workforceRequired: 300,
    baseCost: 800,
    costMultiplier: 1.0,
    levelCostMultiplier: 1.0,
    cityType: 'small',
    economyOfScale: false,
    maxEconomyOfScale: 0,
  },
  logging_camp: {
    id: 'logging_camp',
    category: BuildingCategory.RURAL,
    nameKey: 'building.logging_camp',
    icon: 'building/wood',
    inputs: {},
    outputs: { wood: 120 },
    workforceRequired: 400,
    resourcePotentialRequired: 'wood',
    baseCost: 600,
    costMultiplier: 1.0,
    levelCostMultiplier: 1.0,
    cityType: 'small',
    economyOfScale: true,
    maxEconomyOfScale: 50,
  },

  // Rural - Mining
  coal_mine: {
    id: 'coal_mine',
    category: BuildingCategory.RURAL,
    nameKey: 'building.coal_mine',
    icon: 'building/coal',
    inputs: {},
    outputs: { coal: 100 },
    workforceRequired: 600,
    resourcePotentialRequired: 'coal',
    baseCost: 1500,
    costMultiplier: 1.0,
    levelCostMultiplier: 1.0,
    cityType: 'small',
    economyOfScale: true,
    maxEconomyOfScale: 50,
  },
  iron_mine: {
    id: 'iron_mine',
    category: BuildingCategory.RURAL,
    nameKey: 'building.iron_mine',
    icon: 'building/iron',
    inputs: {},
    outputs: { iron: 80 },
    workforceRequired: 700,
    resourcePotentialRequired: 'iron',
    baseCost: 2000,
    costMultiplier: 1.0,
    levelCostMultiplier: 1.0,
    cityType: 'small',
    economyOfScale: true,
    maxEconomyOfScale: 50,
  },
  lead_mine: {
    id: 'lead_mine',
    category: BuildingCategory.RURAL,
    nameKey: 'building.lead_mine',
    icon: 'building/lead',
    inputs: {},
    outputs: { lead: 60 },
    workforceRequired: 500,
    resourcePotentialRequired: 'lead',
    baseCost: 1200,
    costMultiplier: 1.0,
    levelCostMultiplier: 1.0,
    cityType: 'small',
    economyOfScale: true,
    maxEconomyOfScale: 50,
  },
  sulfur_mine: {
    id: 'sulfur_mine',
    category: BuildingCategory.RURAL,
    nameKey: 'building.sulfur_mine',
    icon: 'building/sulfur',
    inputs: {},
    outputs: { sulfur: 50 },
    workforceRequired: 400,
    resourcePotentialRequired: 'sulfur',
    baseCost: 1000,
    costMultiplier: 1.0,
    levelCostMultiplier: 1.0,
    cityType: 'small',
    economyOfScale: true,
    maxEconomyOfScale: 50,
  },
  gold_mine: {
    id: 'gold_mine',
    category: BuildingCategory.RURAL,
    nameKey: 'building.gold_mine',
    icon: 'building/gold',
    inputs: {},
    outputs: { gold: 20 },
    workforceRequired: 800,
    resourcePotentialRequired: 'gold',
    baseCost: 3000,
    costMultiplier: 1.0,
    levelCostMultiplier: 1.0,
    cityType: 'small',
    economyOfScale: true,
    maxEconomyOfScale: 50,
  },
  oil_derrick: {
    id: 'oil_derrick',
    category: BuildingCategory.RURAL,
    nameKey: 'building.oil_derrick',
    icon: 'building/oil',
    inputs: {},
    outputs: { oil: 40 },
    workforceRequired: 500,
    resourcePotentialRequired: 'oil',
    baseCost: 2500,
    costMultiplier: 1.0,
    levelCostMultiplier: 1.0,
    cityType: 'small',
    economyOfScale: true,
    maxEconomyOfScale: 50,
  },

  // Rural - Plantation
  tea_plantation: {
    id: 'tea_plantation',
    category: BuildingCategory.RURAL,
    nameKey: 'building.tea_plantation',
    icon: 'building/tea',
    inputs: {},
    outputs: { tea: 40 },
    workforceRequired: 400,
    arableLandRequired: 4,
    baseCost: 800,
    costMultiplier: 1.0,
    levelCostMultiplier: 1.0,
    cityType: 'small',
    economyOfScale: true,
    maxEconomyOfScale: 30,
  },
  coffee_plantation: {
    id: 'coffee_plantation',
    category: BuildingCategory.RURAL,
    nameKey: 'building.coffee_plantation',
    icon: 'building/coffee',
    inputs: {},
    outputs: { coffee: 35 },
    workforceRequired: 350,
    arableLandRequired: 3,
    baseCost: 750,
    costMultiplier: 1.0,
    levelCostMultiplier: 1.0,
    cityType: 'small',
    economyOfScale: true,
    maxEconomyOfScale: 30,
  },
  tobacco_plantation: {
    id: 'tobacco_plantation',
    category: BuildingCategory.RURAL,
    nameKey: 'building.tobacco_plantation',
    icon: 'building/tobacco',
    inputs: {},
    outputs: { tobacco: 45 },
    workforceRequired: 300,
    arableLandRequired: 3,
    baseCost: 700,
    costMultiplier: 1.0,
    levelCostMultiplier: 1.0,
    cityType: 'small',
    economyOfScale: true,
    maxEconomyOfScale: 30,
  },
  silk_plantation: {
    id: 'silk_plantation',
    category: BuildingCategory.RURAL,
    nameKey: 'building.silk_plantation',
    icon: 'building/silk',
    inputs: {},
    outputs: { silk: 25 },
    workforceRequired: 250,
    arableLandRequired: 2,
    baseCost: 900,
    costMultiplier: 1.0,
    levelCostMultiplier: 1.0,
    cityType: 'small',
    economyOfScale: true,
    maxEconomyOfScale: 30,
  },
  vine_plantation: {
    id: 'vine_plantation',
    category: BuildingCategory.RURAL,
    nameKey: 'building.vine_plantation',
    icon: 'building/vine',
    inputs: {},
    outputs: { wine: 30 },
    workforceRequired: 280,
    arableLandRequired: 2,
    baseCost: 850,
    costMultiplier: 1.0,
    levelCostMultiplier: 1.0,
    cityType: 'small',
    economyOfScale: true,
    maxEconomyOfScale: 30,
  },

  // Urban - Manufacturing
  fabric_manufactory: {
    id: 'fabric_manufactory',
    category: BuildingCategory.URBAN,
    nameKey: 'building.fabric_manufactory',
    icon: 'building/fabric',
    inputs: { wood: 15 },
    outputs: { fabric: 80 },
    workforceRequired: 250,
    baseCost: 1000,
    costMultiplier: 1.0,
    levelCostMultiplier: 1.0,
    cityType: 'medium',
    economyOfScale: true,
    maxEconomyOfScale: 50,
  },
  textile_mill: {
    id: 'textile_mill',
    category: BuildingCategory.URBAN,
    nameKey: 'building.textile_mill',
    icon: 'building/textile',
    inputs: { wood: 20, fabric: 10 },
    outputs: { textiles: 50 },
    workforceRequired: 300,
    baseCost: 1200,
    costMultiplier: 1.0,
    levelCostMultiplier: 1.0,
    cityType: 'medium',
    economyOfScale: true,
    maxEconomyOfScale: 50,
  },
  steel_mill: {
    id: 'steel_mill',
    category: BuildingCategory.URBAN,
    nameKey: 'building.steel_mill',
    icon: 'building/steel',
    inputs: { coal: 50, iron: 30 },
    outputs: { steel: 40 },
    workforceRequired: 500,
    baseCost: 3000,
    costMultiplier: 1.0,
    levelCostMultiplier: 1.0,
    cityType: 'large',
    economyOfScale: true,
    maxEconomyOfScale: 50,
  },
  tooling_workshop: {
    id: 'tooling_workshop',
    category: BuildingCategory.URBAN,
    nameKey: 'building.tooling_workshop',
    icon: 'building/tools',
    inputs: { wood: 15, iron: 10 },
    outputs: { small_arms: 30 },
    workforceRequired: 200,
    baseCost: 1500,
    costMultiplier: 1.0,
    levelCostMultiplier: 1.0,
    cityType: 'medium',
    economyOfScale: true,
    maxEconomyOfScale: 40,
  },
  ammunition_factory: {
    id: 'ammunition_factory',
    category: BuildingCategory.URBAN,
    nameKey: 'building.ammunition_factory',
    icon: 'building/ammo',
    inputs: { coal: 20, lead: 15 },
    outputs: { ammunition: 40 },
    workforceRequired: 250,
    baseCost: 1800,
    costMultiplier: 1.0,
    levelCostMultiplier: 1.0,
    cityType: 'medium',
    economyOfScale: true,
    maxEconomyOfScale: 40,
  },
  artillery_foundry: {
    id: 'artillery_foundry',
    category: BuildingCategory.URBAN,
    nameKey: 'building.artillery_foundry',
    icon: 'building/artillery',
    inputs: { coal: 40, steel: 25 },
    outputs: { artillery: 20 },
    workforceRequired: 350,
    baseCost: 2500,
    costMultiplier: 1.0,
    levelCostMultiplier: 1.0,
    cityType: 'large',
    economyOfScale: true,
    maxEconomyOfScale: 30,
  },
  shipyard: {
    id: 'shipyard',
    category: BuildingCategory.URBAN,
    nameKey: 'building.shipyard',
    icon: 'building/ship',
    inputs: { wood: 80, iron: 30 },
    outputs: { warships: 10 },
    workforceRequired: 400,
    baseCost: 3500,
    costMultiplier: 1.0,
    levelCostMultiplier: 1.0,
    cityType: 'large',
    economyOfScale: true,
    maxEconomyOfScale: 20,
  },
  rubber_works: {
    id: 'rubber_works',
    category: BuildingCategory.URBAN,
    nameKey: 'building.rubber_works',
    icon: 'building/rubber',
    inputs: {},
    outputs: { rubber: 50 },
    workforceRequired: 200,
    baseCost: 1200,
    costMultiplier: 1.0,
    levelCostMultiplier: 1.0,
    cityType: 'medium',
    economyOfScale: true,
    maxEconomyOfScale: 40,
  },

  // Infrastructure
  railway: {
    id: 'railway',
    category: BuildingCategory.INFRASTRUCTURE,
    nameKey: 'building.railway',
    icon: 'building/rail',
    inputs: { iron: 10, wood: 5 },
    outputs: {},
    workforceRequired: 200,
    baseCost: 2000,
    costMultiplier: 1.0,
    levelCostMultiplier: 2.0,
    cityType: 'none',
    economyOfScale: false,
    maxEconomyOfScale: 0,
  },
  port: {
    id: 'port',
    category: BuildingCategory.INFRASTRUCTURE,
    nameKey: 'building.port',
    icon: 'building/port',
    inputs: {},
    outputs: {},
    workforceRequired: 150,
    baseCost: 1500,
    costMultiplier: 1.0,
    levelCostMultiplier: 1.5,
    cityType: 'medium',
    economyOfScale: false,
    maxEconomyOfScale: 0,
  },
  road: {
    id: 'road',
    category: BuildingCategory.INFRASTRUCTURE,
    nameKey: 'building.road',
    icon: 'building/road',
    inputs: {},
    outputs: {},
    workforceRequired: 50,
    baseCost: 500,
    costMultiplier: 1.0,
    levelCostMultiplier: 1.5,
    cityType: 'none',
    economyOfScale: false,
    maxEconomyOfScale: 0,
  },

  // Government
  government_administration: {
    id: 'government_administration',
    category: BuildingCategory.GOVERNMENT,
    nameKey: 'building.gov_admin',
    icon: 'building/admin',
    inputs: {},
    outputs: {},
    workforceRequired: 100,
    baseCost: 500,
    costMultiplier: 1.0,
    levelCostMultiplier: 1.0,
    cityType: 'none',
    economyOfScale: false,
    maxEconomyOfScale: 0,
  },
  barracks: {
    id: 'barracks',
    category: BuildingCategory.GOVERNMENT,
    nameKey: 'building.barracks',
    icon: 'building/military',
    inputs: { small_arms: 5 },
    outputs: {},
    workforceRequired: 200,
    baseCost: 1000,
    costMultiplier: 1.0,
    levelCostMultiplier: 1.0,
    cityType: 'none',
    economyOfScale: false,
    maxEconomyOfScale: 0,
  },
  barracks_large: {
    id: 'barracks_large',
    category: BuildingCategory.GOVERNMENT,
    nameKey: 'building.barracks_large',
    icon: 'building/military_large',
    inputs: { small_arms: 10, ammunition: 5 },
    outputs: {},
    workforceRequired: 500,
    baseCost: 2500,
    costMultiplier: 1.0,
    levelCostMultiplier: 1.0,
    cityType: 'none',
    economyOfScale: false,
    maxEconomyOfScale: 0,
  },
  naval_base: {
    id: 'naval_base',
    category: BuildingCategory.GOVERNMENT,
    nameKey: 'building.naval_base',
    icon: 'building/naval',
    inputs: {},
    outputs: {},
    workforceRequired: 150,
    baseCost: 1500,
    costMultiplier: 1.0,
    levelCostMultiplier: 1.0,
    cityType: 'none',
    economyOfScale: false,
    maxEconomyOfScale: 0,
  },

  // Development
  construction_sector: {
    id: 'construction_sector',
    category: BuildingCategory.DEVELOPMENT,
    nameKey: 'building.construction',
    icon: 'building/construct',
    inputs: { wood: 30, textiles: 10 },
    outputs: {},
    workforceRequired: 400,
    baseCost: 2000,
    costMultiplier: 1.0,
    levelCostMultiplier: 1.0,
    cityType: 'large',
    economyOfScale: true,
    maxEconomyOfScale: 50,
  },
  trade_center: {
    id: 'trade_center',
    category: BuildingCategory.DEVELOPMENT,
    nameKey: 'building.trade',
    icon: 'building/trade',
    inputs: {},
    outputs: {},
    workforceRequired: 200,
    baseCost: 1500,
    costMultiplier: 1.0,
    levelCostMultiplier: 1.0,
    cityType: 'large',
    economyOfScale: true,
    maxEconomyOfScale: 50,
  },
  university: {
    id: 'university',
    category: BuildingCategory.DEVELOPMENT,
    nameKey: 'building.university',
    icon: 'building/university',
    inputs: {},
    outputs: {},
    workforceRequired: 150,
    baseCost: 2000,
    costMultiplier: 1.0,
    levelCostMultiplier: 1.0,
    cityType: 'large',
    economyOfScale: true,
    maxEconomyOfScale: 50,
  },
};